# Generated by Django 2.1.4 on 2018-12-24 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmpresaAprof', '0002_auto_20181224_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='professor',
        ),
        migrations.AddField(
            model_name='professor',
            name='turma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EmpresaAprof.Turma'),
            preserve_default=False,
        ),
    ]
