# Generated by Django 2.1.4 on 2018-12-25 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpresaAprof', '0004_auto_20181224_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='valor_hora_aula',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='valor da aula por hora'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='hora_inicio',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='turma',
            name='hora_termino',
            field=models.TimeField(),
        ),
    ]
