# Generated by Django 2.1.4 on 2018-12-25 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpresaAprof', '0006_auto_20181224_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(choices=[('Contabilidade', 'Contabilidade'), ('Informática', 'Informática'), ('Administração', 'Administração'), ('Análises Clínicas', 'Análises Clínicas'), ('Outros', 'Outros')], max_length=50, verbose_name='nome do curso'),
        ),
    ]
